AWS_ACCESS_KEY_ID = "AKIA55UOFVRRLWTNIUX7"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-1"
profile_name="MikesCli"
knowledge_base_id="NVPXEKTFCQ"
llm_model = "amazon-titan"
opensearch_host="hjwyh8rjvcdfvtin5ybg.us-east-1.aoss.amazonaws.com"
vector_index_name="vector-index-br-hack-02"
vector_field_name="vectors"
model_id="anthropic.claude-3-5-haiku-20241022-v1:0"
